/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import modelo.Conexion;

/**
 *
 * @author shinee
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        btnGroup.add(radioBtnHombre);
        btnGroup.add(radioBtnMujer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        etiquetaTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        radioBtnHombre = new javax.swing.JRadioButton();
        radioBtnMujer = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        spinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        checkBoxTennis = new javax.swing.JCheckBox();
        checkBoxBasquet = new javax.swing.JCheckBox();
        checkBoxNatacion = new javax.swing.JCheckBox();
        btnInsertarRegistro = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiquetaTitulo.setText("Formulario");

        jLabel1.setText("Seleccione género:");

        radioBtnHombre.setText("Hombre");
        radioBtnHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnHombreActionPerformed(evt);
            }
        });

        radioBtnMujer.setText("Mujer");
        radioBtnMujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMujerActionPerformed(evt);
            }
        });

        jLabel2.setText("¿Cuál es su edad?");

        jLabel3.setText("Seleccione los deportes favoritos:");

        checkBoxTennis.setText("tennis");
        checkBoxTennis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxTennisActionPerformed(evt);
            }
        });

        checkBoxBasquet.setText("Basquet");
        checkBoxBasquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxBasquetActionPerformed(evt);
            }
        });

        checkBoxNatacion.setText("Natación");
        checkBoxNatacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxNatacionActionPerformed(evt);
            }
        });

        btnInsertarRegistro.setText("Insertar Registro");
        btnInsertarRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarRegistroActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(etiquetaTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioBtnMujer, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(radioBtnHombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertarRegistro)
                                .addGap(18, 18, 18)
                                .addComponent(btnMostrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(checkBoxTennis)
                            .addComponent(checkBoxBasquet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(checkBoxNatacion, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(etiquetaTitulo)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnHombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(radioBtnMujer)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addComponent(checkBoxTennis)
                .addGap(18, 18, 18)
                .addComponent(checkBoxBasquet)
                .addGap(18, 18, 18)
                .addComponent(checkBoxNatacion)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarRegistro)
                    .addComponent(btnMostrar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnHombreActionPerformed

    private void radioBtnMujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMujerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBtnMujerActionPerformed

    private void checkBoxTennisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxTennisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxTennisActionPerformed

    private void checkBoxBasquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxBasquetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxBasquetActionPerformed

    private void checkBoxNatacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxNatacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxNatacionActionPerformed

    private void btnInsertarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarRegistroActionPerformed
        Conexion con = new Conexion();
        PreparedStatement ps = null;
        String genero = "";
        int edad = 0;
        boolean tennis = false;
        boolean natacion = false;
        boolean basquet = false;
        
        //JRadio botones
        if(radioBtnHombre.isSelected() == true){
            genero = "Hombre";
        }else if (radioBtnMujer.isSelected() == true){
            genero = "Mujer";
        }
        
        //spinner
        edad = (int) spinner.getValue();
        
        //checkBox
        
        if(checkBoxBasquet.isSelected() == true ){
            basquet = true;
        }
        
        if(checkBoxNatacion.isSelected() == true){
            natacion = true;
        }
        
        if(checkBoxTennis.isSelected() == true){
            tennis = true;
        
        }
        try{
            Connection conexion = con.getConnection();
            ps = conexion.prepareStatement("insert into gustospersona (genero, edad, tennis, basquet, natacion) values (?,?,?,?,?)");
            ps.setString(1, genero);
            ps.setInt(2,edad);
            ps.setBoolean(3, tennis);
            ps.setBoolean(4, basquet);
            ps.setBoolean(5, natacion);
            
            ps.executeUpdate();
            
            conexion.close();
            
            JOptionPane.showMessageDialog(null, "Formulario insertado correctamente");
        }catch(Exception ex){
            System.err.println("Error "+ex);
        }
        
    }//GEN-LAST:event_btnInsertarRegistroActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        Conexion con = new Conexion();
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        try{
            Connection conexion = con.getConnection();
            ps = conexion.prepareStatement("select genero, edad, tennis, basquet, natacion from gustospersona where id=?");
            ps.setInt(1,2);
            rs = ps.executeQuery();
            
            while(rs.next()){
                if(rs.getString("genero").equals("Hombre")){
                    radioBtnHombre.setSelected(true);
                }
                else if(rs.getString("genero").equals("Mujer")){
                    radioBtnMujer.setSelected(true);
                }
                
                spinner.setValue(rs.getInt("edad"));
                
                if(rs.getBoolean("tennis") == true){
                    checkBoxTennis.setSelected(true);
                }
                if(rs.getBoolean("basquet") == true){
                    checkBoxBasquet.setSelected(true);
                }
                if(rs.getBoolean("natacion") == true){
                    checkBoxNatacion.setSelected(true);
                }
            }
            conexion.close();
            
        }catch(Exception ex){
            System.err.println("Error "+ex);
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup;
    private javax.swing.JButton btnInsertarRegistro;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JCheckBox checkBoxBasquet;
    private javax.swing.JCheckBox checkBoxNatacion;
    private javax.swing.JCheckBox checkBoxTennis;
    private javax.swing.JLabel etiquetaTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton radioBtnHombre;
    private javax.swing.JRadioButton radioBtnMujer;
    private javax.swing.JSpinner spinner;
    // End of variables declaration//GEN-END:variables
}
